apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: prometheus-stack
  namespace: monitoring

resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml

# 適用順序を制御するためのパッチ
patches:
  - target:
      kind: HelmRelease
      name: prometheus-stack
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: prometheus-stack
        namespace: monitoring
        annotations:
          # HelmRepositoryが先に作成されるまで待機
          kustomize.toolkit.fluxcd.io/depends-on: monitoring/prometheus-community 
