apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - grafana.yaml

commonLabels:
  app.kubernetes.io/name: monitoring
  app.kubernetes.io/component: prometheus-stack 
