apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  labels:
    app: haproxy
data:
  haproxy.cfg: |
    global
        daemon
        log stdout local0
        maxconn 4096

    defaults
        mode tcp
        timeout connect 5000ms
        timeout client 50000ms
        timeout server 50000ms
        log global

    # ヘルスチェック用のHTTPリスナー
    frontend health_check
        bind *:8080
        mode http
        http-request return status 200

    # RDP用のTCPフォワード設定
    frontend rdp_frontend
        bind *:3389
        mode tcp
        default_backend rdp_backend

    backend rdp_backend
        mode tcp
        balance roundrobin
        server rdp_server1 192.168.11.176:3389

    # 統計情報表示用（オプション）
    frontend stats
        bind *:8404
        mode http
        stats enable
        stats uri /stats
        stats refresh 10s 
