apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
  labels:
    app: haproxy
spec:
  type: ClusterIP
  selector:
    app: haproxy
  ports:
  - name: rdp
    port: 3389
    targetPort: 3389
    protocol: TCP
  - name: health
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: stats
    port: 8404
    targetPort: 8404
    protocol: TCP 
